routes/web.php
<?php

use Gallery\Http\Controllers\FrontController;
use Gallery\Models\GallerySettings;
use Illuminate\Support\Facades\Route;
use \Gallery\Http\Controllers\PhotoGalleryController;


Route::middleware('web')->group(function (){
    Route::middleware('is_admin')->group(function () {
        Route::group(['prefix' => 'admin', 'as' => 'admin.'], static function() {
            Route::resource('photo_gallery',PhotoGalleryController::class);

            Route::group(['prefix' => 'photo_gallery', 'as' => 'photo_gallery.'], static function() {
                Route::post('settings',[PhotoGalleryController::class ,'settings'])->name('settings');
                Route::post('image_store/{category}', [PhotoGalleryController::class, 'storeImage'])->name('image_store');
                Route::post('image_edit/{image}', [PhotoGalleryController::class, 'updateImage'])->name('image_edit');
                Route::delete('image_delete/{image}', [PhotoGalleryController::class, 'destroyImage'])->name('image_delete');
            });
        });
    });
    try {
        $settings = GallerySettings::query()->find(1);
        $url = 'examples';
        if ($settings)
            $url = $settings->url;
        Route::get('/'.$url,[FrontController::class,'index'])->name('gallery');
        Route::get('/'.$url.'/{categoryId}',[FrontController::class,'show'])->name('gallery_show');
    }catch (Exception $exception)
    {

    }
});

resources/views/gallery/front/album.blade.php
@extends('layouts.inner')
@section('title',$seo_title)
@section('description',$seo_description)
@section('keywords',$seo_keywords)
@section('page',true)
@section('content')
<div class="content">
    <div class="catalog__container">
        <div class="container">
            <x-front.breadcrumbs :breadcrumbs="$breadcrumbs" />
            <h1>{{ $album->title }}</h1>
            <div class="row gphoto">
                @foreach ($photos as $photo)
                <x-gallery::front.album_item :photo="$photo" :album="$album"/>
                @endforeach
            </div>
            <div class="pagination-catalog">
                {{ $photos->links() }}
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/gallery/front/index.blade.php
@extends('layouts.inner')
@section('title', $seo_title)
@section('description', $seo_description)
@section('keywords', $seo_keywords)
@section('page', true)
@section('content')
    <div class="content">
        <x-front.elements.breadcrumbs :breadcrumbs="$breadcrumbs" />
        <div class="container">
            <h1>{{ $title }}</h1>
            <div style="margin-bottom: 50px;" class="objects--inner__desc">{{ $description }}</div>
        </div>
        <section class="objects">
            <div class="container objects__container">

                @foreach ($albums as $album)
                    <x-gallery::front.albums :album="$album" />
                @endforeach
            </div>
        </section>
        <section class="pagination__container">
            {{ $albums->links('pagination::bootstrap-4') }}
        </section>
    </div>
@endsection

resources/views/gallery/index.blade.php
@extends('layouts.admin')
@section('title', 'Фотогалерея')
@section('content')
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"
    />
    <div class="card">
        <div class="card">
            <x-admin.navigatin-js :links="$links" />
            <div class="card-body">
                <div class="tab-content">
                    <x-gallery::gallery />
                    <x-gallery::settings />
                </div>
            </div>
        </div>
    </div>

    <script src="{{ asset('assets/plugins/gallery/lightgallery.js') }}"></script>
    <script src="{{ asset('assets/plugins/gallery/lightgallery-1.js') }}"></script>
    <script src="{{ asset('assets/js/admin/utils/files.js') }}"></script>
    <script >
        Fancybox.bind("[data-fancybox]", {
            // Your custom options
        });
        filesClass.galleryAdmin()
    </script>
@endsection
@section("breadcrumb")
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            <li class="breadcrumb-item active" aria-current="page">Фотогалерея</li>
        </ol>
    </div>
@endsection

resources/views/gallery/show.blade.php
@extends('layouts.admin')
@section('title', 'Фотогалерея')
@section('content')
    <script src="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.umd.js"></script>
    <link
        rel="stylesheet"
        href="https://cdn.jsdelivr.net/npm/@fancyapps/ui@5.0/dist/fancybox/fancybox.css"
    />
    <div class="card">
        <div class="card-header card-header-divider">
            <div>
                <h3 class="card-title">Фотографии</h3>
            </div>
        </div>
        <div class="card-body">
            <x-warning />
            <div class="row">
                <div class="col-lg-8">
                    <x-gallery::images :categoryId="$categoryId"/>
                </div>
                <div class="col-lg-4">
                    <input type="hidden" id="image" value="{{$categoryId}}">
                    <h5 class="mb-4 category_form_title"><i class="fas fa-plus-circle"></i> Добавить фото</h5>
                    <form action="{{ route('admin.photo_gallery.image_store',['category'=>$categoryId]) }}" id="photo_gallery_form" method="POST" enctype="multipart/form-data">
                        @csrf
                        <div id="method"></div>
                        <input type="hidden" name="id" id="id_edit" value="">
                        <div class="form-group">
                            <label for="title">Заголовок</label>
                            <input class="form-control " id="title" value="" name="title" type="text">
                        </div>
                        <div class="form-group">
                            <label for="description">Описание</label>
                            <textarea class="form-control " id="description" name="description" type="text"></textarea>
                        </div>
                        <div class="form-group">
                            <label class="custom-switch ps-0">
                                <input type="checkbox" id="order" class="custom-switch-input">
                                <span class="custom-switch-indicator me-3"></span>
                                <span class="custom-switch-description mg-l-10">Переместить фото</span>
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="image_url">Фото</label>
                            <input type="file" class="filepond " name="images[]" multiple>
                        </div>
                        <div class="pb-0 mt-3">
                            <div class="files-unstyled">
                            </div>
                        </div>
                        <button type="submit" name="save" class="btn btn-sm btn-success">Сохранить</button>
                        <button type="submit" name="save" class="btn btn-sm btn-danger edit_close d-none">Отмена</button>
                    </form>

                </div>
            </div>
        </div>
    </div>

    <script src="{{ asset('assets/plugins/gallery/lightgallery.js') }}"></script>
    <script src="{{ asset('assets/plugins/gallery/lightgallery-1.js') }}"></script>
    <script src="{{ asset('assets/js/admin/utils/files.js') }}"></script>
    <script >
        Fancybox.bind("[data-fancybox]", {
            // Your custom options
        });
        filesClass.galleryAdmin()
    </script>
@endsection
@section('breadcrumb')
    <div>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{route("admin.index")}}">Главная</a></li>
            @if(count($breadcrumb)>0)
                <li class="breadcrumb-item"><a href="{{route("admin.photo_gallery.index")}}">Фотогалерея</a></li>
                @foreach($breadcrumb as $item)
                        <li class="breadcrumb-item active" aria-current="page">{{$item['title']}}</li>
                @endforeach
            @else
                <li class="breadcrumb-item active" aria-current="page">Каталог</li>
            @endif
        </ol>
    </div>
@endsection